const products = [
    {
        id: 1,
        imgs: ["https://i.postimg.cc/ZRynchJY/Green-Leaf-Lettuce-each.jpg"],
        sku: "E0234",
        title: "Green Leaf Lettuce",
        description: "Most fresh vegetables are low in calories and have a water content in excess of 70 percent, with only about 3.5 percent protein and less than 1 percent fat. ... The root vegetables include beets, carrots, radishes, sweet potatoes, and turnips. Stem vegetables include asparagus and kohlrabi.",
        type: "Fruit & vegetable",
        unit: "each",
        published : true,
        quantity: 70,
        price: 12,
        salePrice: 10,
        tags: ["grocery"]
    },
    {
        id: 2,
        imgs: ["https://i.postimg.cc/MTPyNwQC/Clementine-5ct.jpg"],
        sku: "E02342",
        title: "Rainbow Chard",
        description: "Most fresh vegetables are low in calories and have a water content in excess of 70 percent, with only about 3.5 percent protein and less than 1 percent fat. ... The root vegetables include beets, carrots, radishes, sweet potatoes, and turnips. Stem vegetables include asparagus and kohlrabi.",
        type: "Organic Food",
        unit: "each",
        published : true,
        quantity: 70,
        price: 8,
        salePrice: 12,
        tags: ["grocery"]
    },
    {
        id: 3,
        imgs: ["https://i.postimg.cc/MTPyNwQC/Clementine-5ct.jpg"],
        sku: "E02342",
        title: "Rainbow Chard",
        description: "Most fresh vegetables are low in calories and have a water content in excess of 70 percent, with only about 3.5 percent protein and less than 1 percent fat. ... The root vegetables include beets, carrots, radishes, sweet potatoes, and turnips. Stem vegetables include asparagus and kohlrabi.",
        type: "Organic Food",
        unit: "each",
        published : true,
        quantity: 70,
        price: 8,
        salePrice: 12,
        tags: ["grocery"]
    },
    {
        id: 4,
        imgs: ["https://i.postimg.cc/MTPyNwQC/Clementine-5ct.jpg"],
        sku: "E02342",
        title: "Rainbow Chard",
        description: "Most fresh vegetables are low in calories and have a water content in excess of 70 percent, with only about 3.5 percent protein and less than 1 percent fat. ... The root vegetables include beets, carrots, radishes, sweet potatoes, and turnips. Stem vegetables include asparagus and kohlrabi.",
        type: "Organic Food",
        unit: "each",
        published : true,
        quantity: 70,
        price: 8,
        salePrice: 12,
        tags: ["grocery"]
    },
    {
        id: 5,
        imgs: ["https://i.postimg.cc/MTPyNwQC/Clementine-5ct.jpg"],
        sku: "E02342",
        title: "Rainbow Chard",
        description: "Most fresh vegetables are low in calories and have a water content in excess of 70 percent, with only about 3.5 percent protein and less than 1 percent fat. ... The root vegetables include beets, carrots, radishes, sweet potatoes, and turnips. Stem vegetables include asparagus and kohlrabi.",
        type: "Organic Food",
        unit: "each",
        published : true,
        quantity: 70,
        price: 8,
        salePrice: 12,
        tags: ["grocery"]
    },
    {
        id: 6,
        imgs: ["https://i.postimg.cc/MTPyNwQC/Clementine-5ct.jpg"],
        sku: "E02342",
        title: "Rainbow Chard",
        description: "Most fresh vegetables are low in calories and have a water content in excess of 70 percent, with only about 3.5 percent protein and less than 1 percent fat. ... The root vegetables include beets, carrots, radishes, sweet potatoes, and turnips. Stem vegetables include asparagus and kohlrabi.",
        type: "Organic Food",
        unit: "each",
        published : true,
        quantity: 70,
        price: 8,
        salePrice: 12,
        tags: ["grocery"]
    },
    {
        id: 7,
        imgs: ["https://i.postimg.cc/MTPyNwQC/Clementine-5ct.jpg"],
        sku: "E02342",
        title: "Rainbow Chard",
        description: "Most fresh vegetables are low in calories and have a water content in excess of 70 percent, with only about 3.5 percent protein and less than 1 percent fat. ... The root vegetables include beets, carrots, radishes, sweet potatoes, and turnips. Stem vegetables include asparagus and kohlrabi.",
        type: "Organic Food",
        unit: "each",
        published : true,
        quantity: 70,
        price: 8,
        salePrice: 12,
        tags: ["grocery"]
    },
    {
        id: 8,
        imgs: ["https://i.postimg.cc/MTPyNwQC/Clementine-5ct.jpg"],
        sku: "E02342",
        title: "Rainbow Chard",
        description: "Most fresh vegetables are low in calories and have a water content in excess of 70 percent, with only about 3.5 percent protein and less than 1 percent fat. ... The root vegetables include beets, carrots, radishes, sweet potatoes, and turnips. Stem vegetables include asparagus and kohlrabi.",
        type: "Organic Food",
        unit: "each",
        published : true,
        quantity: 70,
        price: 8,
        salePrice: 12,
        tags: ["grocery"]
    },
    {
        id:9,
        imgs: ["https://i.postimg.cc/MTPyNwQC/Clementine-5ct.jpg"],
        sku: "E02342",
        title: "Rainbow Chard",
        description: "Most fresh vegetables are low in calories and have a water content in excess of 70 percent, with only about 3.5 percent protein and less than 1 percent fat. ... The root vegetables include beets, carrots, radishes, sweet potatoes, and turnips. Stem vegetables include asparagus and kohlrabi.",
        type: "Organic Food",
        unit: "each",
        published : true,
        quantity: 70,
        price: 8,
        salePrice: 12,
        tags: ["grocery"]
    },
    {
        id: 10,
        imgs: ["https://i.postimg.cc/MTPyNwQC/Clementine-5ct.jpg"],
        sku: "E02342",
        title: "Rainbow Chard",
        description: "Most fresh vegetables are low in calories and have a water content in excess of 70 percent, with only about 3.5 percent protein and less than 1 percent fat. ... The root vegetables include beets, carrots, radishes, sweet potatoes, and turnips. Stem vegetables include asparagus and kohlrabi.",
        type: "Organic Food",
        unit: "each",
        published : true,
        quantity: 70,
        price: 8,
        salePrice: 12,
        tags: ["grocery"]
    }
]
export default products